pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                withMaven(maven : 'maven') {
                    sh 'mvn -B -DskipTests clean package'
                }
            }
        }
/*         // stage('Test') {
        //     steps {
        //         withMaven(maven : 'maven') {
        //             //sh 'mvn test'
        //         }
        //     }
        //     post {
        //         always {
        //             junit 'target/surefire-reports/*.xml'
        //         }
        //     }
        // } */
stage('Analyse des étapes') {
  steps {
    sh '''
      echo "Analyse des étapes Jenkins" > steps_report.txt
      cat "$BUILD_LOG"
'''
  }
}



    }
}
