name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# allow the workflow to push the updated pom.xml back to your repo
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          caceh: 'maven'

      # ---- 2a: bump PATCH automatically to 1.0.<run_number> ----
      - name: Set Maven version to 1.0.${{ github.run_number }}
        run: |
          mvn -q versions:set -DnewVersion=1.0.${{ github.run_number }}
          mvn -q versions:commit
          echo "Effective version:" && mvn -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build Docker image
        run: docker build -t simple-java-maven-app:1.0.${{ github.run_number }} .
